// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 ElcanoTek, Inc.
"use strict";
const fs = require("node:fs");
const path = require("node:path");

function settings(env = process.env) {
  const values = Object.fromEntries(["APP_DIR", "APP_USER", "INSTALL_SRC_DIR", "ENV_FILE", "CLI_TARGET", "PORT", "PAGES_INSTALL_CONFIG"].map((key) => [key, env[key]]));
  for (const key of ["APP_DIR", "INSTALL_SRC_DIR", "ENV_FILE", "CLI_TARGET", "PAGES_INSTALL_CONFIG"]) {
    if (!/^\/[A-Za-z0-9_./-]+$/.test(values[key] || "") || values[key].split("/").includes("..")) {
      throw new Error(`${key} must be an absolute path containing only letters, digits, /, _, . and -`);
    }
  }
  if (!/^[a-z_][a-z0-9_-]*\$?$/.test(values.APP_USER || "")) throw new Error("APP_USER must be a system account name");
  if (!/^\d+$/.test(values.PORT || "") || Number(values.PORT) < 1 || Number(values.PORT) > 65535) throw new Error("PORT must be between 1 and 65535");
  return values;
}

function render(kind, env = process.env) {
  const v = settings(env);
  const deploy = path.join(__dirname, "..", "deploy");
  if (kind === "config") {
    const names = { PAGES_APP_DIR: v.APP_DIR, PAGES_APP_USER: v.APP_USER, PAGES_SRC_DIR: v.INSTALL_SRC_DIR, PAGES_ENV_FILE: v.ENV_FILE, PAGES_CLI_TARGET: v.CLI_TARGET };
    return "# Pages installation defaults; generated by bootstrap. Contains no credentials.\n" +
      Object.entries(names).map(([key, value]) => `${key}="\${${key}:-${value}}"`).join("\n") + "\n";
  }
  if (kind === "service") return fs.readFileSync(path.join(deploy, "pages.service"), "utf8")
    .replace(/^User=.*$/m, `User=${v.APP_USER}`).replace(/^Group=.*$/m, `Group=${v.APP_USER}`)
    .replace(/^WorkingDirectory=.*$/m, `WorkingDirectory=${v.APP_DIR}`)
    .replace(/^EnvironmentFile=.*$/m, `EnvironmentFile=${v.ENV_FILE}`)
    .replace(/^ReadWritePaths=.*$/m, `ReadWritePaths=${v.APP_DIR}/assets`);
  if (kind === "cli") return fs.readFileSync(path.join(deploy, "pages-cli"), "utf8")
    .replaceAll("/etc/default/pages-install", v.PAGES_INSTALL_CONFIG);
  if (kind === "caddy") {
    for (const key of ["DASHBOARD_HOST", "CONTENT_HOST"]) {
      if (!/^[a-z0-9.-]+$/i.test(env[key] || "")) throw new Error(`${key} must be a hostname`);
    }
    return fs.readFileSync(path.join(deploy, "pages.caddy"), "utf8")
      .replaceAll("{{DASHBOARD_HOST}}", env.DASHBOARD_HOST).replaceAll("{{CONTENT_HOST}}", env.CONTENT_HOST)
      .replaceAll("127.0.0.1:3002", `127.0.0.1:${v.PORT}`);
  }
  if (kind === "check") return "";
  throw new Error(`unknown installation template: ${kind}`);
}

if (require.main === module) {
  try { process.stdout.write(render(process.argv[2])); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { render };
